export default `
  type User { 
		id: String,
		firstName: String, 
		lastName: String, 
		email: String, 
		token: String,
		image: String,
		created: Boolean,
	}

	type Query { 
		users(token: String!): User 
	}
  
	type Mutation {
	  addUser(
			firstName: String!, 
			lastName: String!, 
			email: String!, 
			token: String!,
			image: String,
			created: Boolean,
		): User
	}
`;