export default `
  type User { 
		id: String,
		firstName: String, 
		lastName: String, 
		email: String, 
		token: String,
		image: String,
		created: Boolean,
	}

	type Didit {
		id: String,
		userId: String,
		comment: String,
    image: String,
		date: String
		created: Boolean,
		type: Int,
	}

	type Query { 
		users(token: String!): User,
		mydidits(userId: String!): [Didit]
	}
  
	type Mutation {
	  addUser(
			firstName: String!, 
			lastName: String!, 
			email: String!, 
			token: String!,
			image: String,
			created: Boolean,
		): User,
		addDidit(
			userId: String!,
			comment: String, 
			type: Int,
			image: String, 
			date: String!, 
			created: Boolean,
		): Didit,
	}
`;